### ISSUE TITLE
Add Examples

### ISSUE THREAD

**Issue by aarongreenlee** [thefabric-io/eventsourcing#3]
First, thank you for sharing this work. Generics seem like a great use case here and I appreciate you sharing your work.

And, I think adding examples will go a long way toward helping others realize value from the work you have shared. I myself am finding some trouble getting my Events to work as I expect. If I could reference an example it would help me ensure I'm setting up my function signatures correctly.

Thank you.

**Comment by jasseem** [comment]
Hi there,

First off, thank you so much for taking the time to send over your feedback and kind words. It’s always encouraging to hear from others who find the work valuable, and I’m glad to know that the generics implementation has caught your interest.

I absolutely agree with your suggestion regarding adding examples to the documentation. Examples can indeed make it significantly easier to understand how to use the features effectively and ensure everything is set up correctly. Your point about making it easier to work with Events and function signatures is well taken.

Given your insights, I’m keen to enhance the documentation with more practical examples that could assist you and others in getting the most out of the project. However, I’d like to inform you that my current availability is quite limited, so there might be a slight delay in implementing these changes and getting back to you with a detailed answer. Please rest assured, though, that your suggestion is on my radar, and I will make it a priority as soon as my schedule allows.

In the meantime, I understand the importance of getting your Events to work as expected. To assist you further, I’d like to offer a quick meeting where we can discuss your current setup and see if we can get you up and running before these changes are pushed to the documentation. Please let me know your availability, and I’ll do my best to accommodate.

Thank you once again for your understanding and support. Your feedback is invaluable, and I’m looking forward to making the project even more user-friendly with your suggested improvements and through direct support.

**Comment by jasseem** [comment]
Hi @aarongreenlee, I managed to find some free time yesterday night and put together a straightforward example for you: https://github.com/thefabric-io/eventsourcing.example. Feel free to take a look and see if it meets your needs.
